server:
  port: 8888

spring:
  cloud:
    config:
      server:
        enabled: true
        git:
          clone-on-start: true
          uri: https://github.com/vikhani/spring-cloud-webinar-demo.git
          search-paths: spring-cloud-webinar-demo-config
          skipSslValidation: true
          default-label: 4_gateway
