apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: clientinfo
  name: clientinfo
spec:
  ports:
    - name: 8081-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: clientinfo
  type: LoadBalancer
status:
  loadBalancer: {}