server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true

spring:
  cloud:
    vault:
      scheme: http
      host: localhost
      port: 8200
      connection-timeout: 5000
      read-timeout: 15000
      authentication: TOKEN
      kv.enabled: true
      enabled: true
      token: 00000000-0000-0000-0000-000000000000
