spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888

---
spring:
  config:
    import: configserver:http://spring-cloud-kubernetes-configserver:8888